redis:
  addr: "192.168.137.5:6379"
  db: 0
  password: ""
database:
  type: "mysql"
  host: "192.168.137.5"
  dbname: "testdb"
  username: "root"
  password: "root"
  port: "3306"
  charset: "utf8mb4"
app:
  jwt-key: "00000000"
