info:
  contact: {}
  license: {}
  title: 接口文档
  version: 0.0.1
paths:
  /users:
    get:
      consumes:
      - application/json
      description: 新增一个用户
      produces:
      - application/json
      summary: 新增用户
swagger: "2.0"
tags:
- description: web框架描述
  name: web框架名称
